
const Facultyimg = "/AsramWebsite-FE/assets/faculty/faculty.png";
const leadership1 = "/AsramWebsite-FE/assets/faculty/facultyleadership1.png";
const leadership2 = "/AsramWebsite-FE/assets/faculty/facultyleadership2.png";
const leadership3 = "/AsramWebsite-FE/assets/faculty/facultyleadership3.png";

// Mock Data for "Leadership"
export const leadershipData = [
    {
        id: 1,
        name: "Dr. Sanjay Malhotra",
        role: "Principal",
        qualifications: "MBBS, MD, FICP",
        specialty: "Medical Education & Administration",
        department: "ASRAM Medical College",
        experience: "28+ years Experience",
        image: leadership1,
        email: "sanjay.malhotra@asram.in",
    },
    {
        id: 2,
        name: "Dr. Priya Sharma",
        role: "Professor & Dean",
        qualifications: "MD (Pathology), PhD",
        specialty: "Hematopathology",
        department: "Department of Pathology",
        experience: "22+ years Experience",
        image: leadership1,
        email: "priya.sharma@asram.in",
    },
    {
        id: 3,
        name: "Mrs. Deepa Thomas",
        role: "Professor & Principal",
        qualifications: "MSc (Nursing), PhD",
        specialty: "Medical-Surgical Nursing",
        department: "College of Nursing",
        experience: "20+ years Experience",
        image: leadership1,
        email: "deepa.thomas@asram.in",
    },
    {
        id: 4,
        name: "Dr. Rajesh Kumar",
        role: "Professor & HOD",
        qualifications: "MD, DM (Cardiology), FACC",
        specialty: "Interventional Cardiology",
        department: "Department of General Medicine",
        experience: "26+ years Experience",
        image: leadership2,
        email: "rajesh.kumar@asram.in",
    },
    {
        id: 5,
        name: "Dr. Vikram Singh",
        role: "Associate Professor & HOD",
        qualifications: "MS (Ortho), DNB, MRCS",
        specialty: "Joint Replacement & Sports Medicine",
        department: "Department of Orthopedics",
        experience: "16+ years Experience",
        image: leadership2,
        email: "vikram.singh@asram.in",
    },
    {
        id: 6,
        name: "Dr. Suresh Nair",
        role: "Professor & HOD",
        qualifications: "MBBS, MD (Anatomy), PhD",
        specialty: "Neuroanatomy",
        department: "Department of Anatomy",
        experience: "24+ years Experience",
        image: leadership2,
        email: "suresh.nair@asram.in",
    },
    {
        id: 7,
        name: "Dr. Amit Gupta",
        role: "Professor & HOD",
        qualifications: "MBBS, MD, PhD",
        specialty: "Clinical Pharmacology",
        department: "Department of Pharmacology",
        experience: "23+ years Experience",
        image: Facultyimg,
        email: "amit.gupta@asram.in",
    },
    {
        id: 8,
        name: "Mr. Karthik Krishnan",
        role: "Associate Professor & HOD",
        qualifications: "MD (Pathology), PhD",
        specialty: "Medical Laboratory Technology",
        department: "College of Paramedical Sciences",
        experience: "14+ years Experience",
        image: Facultyimg,
        email: "karthik.krishnan@asram.in",
    },
    {
        id: 9,
        name: "Dr. Suresh Nair",
        role: "Professor & HOD",
        qualifications: "MBBS, MD (Anatomy), PhD",
        specialty: "Neuroanatomy",
        department: "Department of Anatomy",
        experience: "24+ years Experience",
        image: Facultyimg,
        email: "suresh.nair.2@asram.in",
    },
];

// Mock Data for "Faculty Members"
export const facultyMembersData = [
    {
        id: 101,
        name: "Dr. Anjali Desai",
        role: "Professor",
        qualifications: "MD, DGO, FICOG",
        specialty: "High-Risk Pregnancy & Infertility",
        department: "Department of OB-GYN",
        experience: "19+ years Experience",
        image: leadership1,
        email: "anjali.desai@asram.in",
    },
    {
        id: 102,
        name: "Dr. Arun Verma",
        role: "Associate Professor",
        qualifications: "MS, MCh (Surgical Oncology)",
        specialty: "Laparoscopic & Oncological Surgery",
        department: "Department of General Surgery",
        experience: "18+ years Experience",
        image: leadership1,
        email: "arun.verma@asram.in",
    },
    {
        id: 103,
        name: "Dr. Kavita Iyer",
        role: "Associate Professor",
        qualifications: "MBBS, MD (Physiology)",
        specialty: "Cardiovascular Physiology",
        department: "Department of Physiology",
        experience: "15+ years Experience",
        image: leadership1,
        email: "kavita.iyer@asram.in",
    },
    {
        id: 104,
        name: "Dr. Lakshmi Menon",
        role: "Associate Professor",
        qualifications: "MBBS, MD (Physiology)",
        specialty: "Cardiovascular Physiology",
        department: "Department of Physiology",
        experience: "15+ years Experience",
        image: Facultyimg,
        email: "lakshmi.menon@asram.in",
    },
    {
        id: 105,
        name: "Dr. Kavita Iyer",
        role: "Associate Professor",
        qualifications: "MBBS, MD (Physiology)",
        specialty: "Cardiovascular Physiology",
        department: "Department of Physiology",
        experience: "15+ years Experience",
        image: Facultyimg,
        email: "kavita.iyer.2@asram.in",
    },
    {
        id: 106,
        name: "Dr. Kavita Iyer",
        role: "Associate Professor",
        qualifications: "MBBS, MD (Physiology)",
        specialty: "Cardiovascular Physiology",
        department: "Department of Physiology",
        experience: "15+ years Experience",
        image: Facultyimg,
        email: "kavita.iyer.3@asram.in",
    },
];
